// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLatestWorkspace():Promise<string>;

export function CurrentProject():Promise<void>;
