// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLatestWorkspace() {
  return window['go']['main']['App']['CheckLatestWorkspace']();
}

export function CurrentProject() {
  return window['go']['main']['App']['CurrentProject']();
}
